### ISSUE TITLE
cosine produces values larger than 1

### ISSUE THREAD

**Issue by rcannood** [koheiw/proxyC#5]
Due to rounding errors, the similarity in the current implementation can be larger than 1. This is not really desired, as calculating for instance cos^-1 will then produce NaNs:
```R
> acos(sim)
2 x 2 Matrix of class "dsyMatrix"
         [,1]     [,2]
[1,]      NaN 0.390607
[2,] 0.390607      NaN
```

Whereas by setting the maximum value to 1, everything will work as intended:
```R
> sim@x[sim@x > 1] <- 1
> acos(sim)
2 x 2 Matrix of class "dsyMatrix"
         [,1]     [,2]
[1,] 0.000000 0.390607
[2,] 0.390607 0.000000
```

This can easily be tested with the following test:
```R
test_that("cosine similarity can't be larger than 1", {
  x <- Matrix::Matrix(c(1, 2, 5, 3), ncol = 2, sparse = TRUE)
  sim <- simil(x, y = NULL, method = "cosine")
  expect_true(all(sim <= 1))
})
```

**Comment by koheiw** [comment]
How about using `zapsmall`?
```r
> getOption("digits")
[1] 7
> zapsmall(1 + 1e-6)
[1] 1.000001
> zapsmall(1 + 1e-7)
[1] 1
```

**Comment by rcannood** [comment]
Cool, I didn't know about `zapsmall()`! It does the job just fine:

```R
library(proxyC)
x <- Matrix::Matrix(c(1, 2, 5, 3), ncol = 2, sparse = TRUE)
sim <- simil(x, y = NULL, method = "cosine")
acos(sim)
## 2 x 2 Matrix of class "dsyMatrix"
##          [,1]     [,2]
## [1,]      NaN 0.390607
## [2,] 0.390607      NaN
## Warning message:
## In acos(x@x) : NaNs produced
sim@x <- zapsmall(sim@x)
acos(sim)
## 2 x 2 Matrix of class "dsyMatrix"
##          [,1]     [,2]
## [1,] 0.000000 0.390607
## [2,] 0.390607 0.000000
```

**Comment by rcannood** [comment]
I don't mind running `zapsmall()` right before calculating the acos, so you don't necessarily have to include it in proxyC. What do you prefer?

**Comment by koheiw** [comment]
I think it is better to make cosine similarity to be precisely up to 1. Adding `zapsmall()` is easy but `getOption("digits")` is also used in `print()`. If we apply `zapsmall()` internally, we have to add a `zapsmall` argument to `proxy()` to avoid taking values from the option. This approach is similar to `digest::sha1()`.
