### ISSUE TITLE
Enable GitHub Pages

### ISSUE THREAD

**Issue by rcannood** [koheiw/proxyC#55]
Hi @koheiw !

Could we enable GitHub Pages for this repository?

I would do it myself, but it seems I don't have the permissions to do so.

The easiest approach is to just run `usethis::use_pkgdown_github_pages()` and commit the resulting files.

Thanks!
Robrecht

**Comment by koheiw** [comment]
That would be great! I enabled the Pages.

![image](https://github.com/user-attachments/assets/7a002d80-aa75-4fab-a8db-c7f90220e898)

**Comment by rcannood** [comment]
Unfortuntely, it seems I need the right permissions in order to run this command, even if GitHub Pages is enabled:

```
> usethis::use_pkgdown_github_pages()
! Overwrite pre-existing file _pkgdown.yml?

1: No way
2: For sure
3: No

Selection: 3
ℹ Leaving _pkgdown.yml unchanged.
☐ Modify _pkgdown.yml.
Error in `gh::gh()`:
! GitHub API error (404): Not Found
✖ URL not found: <https://api.github.com/repos/koheiw/proxyC/pages>
ℹ Read more at <https://docs.github.com/rest/pages/pages#update-information-about-a-apiname-pages-site>
Run `rlang::last_trace()` to see where the error occurred.
```

I created PR #56 containing the partial results of running the command. 

Could you run this command? ALternatively, you could change my access role for this repository from "Write" to "Maintain".

**Comment by koheiw** [comment]
I ran the command and merged your PR. The website is created but images and equations are not displayed correctly.

https://koheiw.github.io/proxyC/

I am happy to give you full access to theis repo, but not sure how. I can only choose "Collaborator".

![image](https://github.com/user-attachments/assets/13efc091-f55b-42c9-92df-9d67561837cb)

**Comment by koheiw** [comment]
I fixed the issues in the pkgdown website. 

https://koheiw.github.io/proxyC/

I built it locally on the master branch, but it could be deployed by Github actions on the gh-pages branch.

**Comment by rcannood** [comment]
> I ran the command and merged your PR. The website is created but images and equations are not displayed correctly.
> 
> https://koheiw.github.io/proxyC/
> 
> I am happy to give you full access to theis repo, but not sure how. I can only choose "Collaborator".
> 
> ![image](https://private-user-images.githubusercontent.com/6572963/376147165-13efc091-f55b-42c9-92df-9d67561837cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNzEwOTcsIm5iZiI6MTcyOTA3MDc5NywicGF0aCI6Ii82NTcyOTYzLzM3NjE0NzE2NS0xM2VmYzA5MS1mNTViLTQyYzktOTJkZi05ZDY3NTYxODM3Y2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTZUMDkyNjM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzBkNjVkYmU2MGNmY2Q5MTk4NjFkZDEwYTBhYmY0YTQyZDgxMWZhMzRlNTRkNjkzN2U3MzIwOTVkYzZiMzdhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5NaorBmMbcc7Tycb33LtGQHDtyWXKBTleEUF8vK-eSI)

Ahh -- good point, apologies. This option is not available because this repository is part of your user account and not an organisation. My bad!

> I fixed the issues in the pkgdown website.
> 
> https://koheiw.github.io/proxyC/
> 
> I built it locally on the master branch, but it could be deployed by Github actions on the gh-pages branch.

Awesome, great work! Thank you so much for taking care of this!

As far as I'm concerned, this looks pretty good to me. Shall I go ahead and close this issue?
